import { eq, sql } from "drizzle-orm";

import { db } from "../db/index.js";
import { startupProfiles, type StartupProfileRow } from "../db/schema.js";
import { HttpError } from "../http/errors.js";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Postgres raises a type error on a malformed uuid, so screen ids here and
 * report the same 404 the caller would get for a well-formed unknown id
 * (a stale profile id in localStorage shouldn't surface as a 500). */
export async function getProfileOr404(profileId: string): Promise<StartupProfileRow> {
  if (!UUID_RE.test(profileId)) {
    throw new HttpError(404, "profile not found");
  }
  const [profile] = await db
    .select()
    .from(startupProfiles)
    .where(eq(startupProfiles.id, profileId))
    .limit(1);
  if (!profile) {
    throw new HttpError(404, "profile not found");
  }
  return profile;
}

/** Every column default is generated by Postgres (`now()`), so updated_at has
 * to come from the same clock -- stamping it with the Node process clock lets
 * an update land *before* created_at whenever the two hosts disagree. */
export const nowSql = sql`now()`;

/** Field updates the generate/research/search endpoints fold back into the
 * shared profile, mirroring the SQLAlchemy `onupdate` on updated_at. */
export async function touchProfile(
  profileId: string,
  patch: Partial<typeof startupProfiles.$inferInsert>,
): Promise<void> {
  await db
    .update(startupProfiles)
    .set({ ...patch, updatedAt: nowSql })
    .where(eq(startupProfiles.id, profileId));
}
